import Head from 'next/head'
import React from 'react'
import Login from './Login/Login'

export default function Header() {
    return (
        <>
            <Head>
                <title>CloudStore</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/textil-hugo.png" />
            </Head>
        </>

    )
}
